name: main

on:
  push:
    tags: [ v* ]
    branches: [ master ]
    paths-ignore:
      - 'README.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

  # In case of some breaking changes in API.
  schedule:
    - cron: '0 13 * * *'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.17'

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Terraform acceptance tests
        timeout-minutes: 10
        env:
          TF_ACC: "1"
          SOLUS_BASE_URL: ${{ secrets.TEST_BASE_URL }}
          SOLUS_TOKEN: ${{ secrets.TEST_TOKEN }}
          SOLUS_TEST_LOCATION_ID: ${{ secrets.TEST_LOCATION_ID }}
          SOLUS_INSECURE: "1"

        run: |
          go test -cover ./internal/provider/
